### ISSUE TITLE
Add Small City Containers for Forecast Display to Enhance User Experience of Different Cities

### ISSUE THREAD

**Issue by Mefisto04** [adaharshsingh/Propacity#17]
To improve the user experience, I propose adding small containers for different cities that, when clicked, will display the weather forecast for the selected city. These city containers can be arranged in a grid or list format, allowing users to easily explore the weather conditions of various locations at a glance. This feature will provide a more interactive and user-friendly approach to checking weather forecasts, reducing navigation time and enhancing accessibility.

Screenshot :
![image](https://github.com/user-attachments/assets/32760e15-4690-4e66-9526-8d7abb54db16)

Below the navbar and above the transperant container
Please assign me this issue/feature so that i can add this and also add hacktoberfest tag

**Comment by adaharshsingh** [comment]
I like the simple layout of this website ; So make sure the city containers don't take very much space ;  you can also go for a collapseable side bar as another issue;
