### ISSUE TITLE
Enhancing Alert Popup 

### ISSUE THREAD

**Issue by AnujKshatriya** [adaharshsingh/Propacity#22]
Adding React Toaster in place of Alert which enhances UI
![open-souce-issue-1](https://github.com/user-attachments/assets/782dc113-65c7-403b-b965-1fd83d1672a1)
![open-source-toast](https://github.com/user-attachments/assets/ec993363-aa51-4621-b9d1-88a2bf8d4af9)

**Comment by AnujKshatriya** [comment]
@adaharshsingh should I make pr for this change ?

**Comment by adaharshsingh** [comment]
yes
