### ISSUE TITLE
Improve the alignment and Navbar color according to the background

### ISSUE THREAD

**Issue by AnujKshatriya** [adaharshsingh/Propacity#24]
Problem : 
Currently navbar color is white and is not changing according to background change which somehow makes UI less attractive also for mobile device the navbar alignment is improper.

Screenshot :  
![navbar-enhancement](https://github.com/user-attachments/assets/a0dda33d-a348-4308-a62c-3d73da2fdce9)

Proposed Solution: 
Adjust the CSS according to weather conditions and background color also improving navbar alignment for mobile view.

Additional context:
Please assign this issue to me, and kindly add the Hacktoberfest tag for tracking.

**Comment by AnujKshatriya** [comment]
@adaharshsingh I have updated the navbar color to align with the footer and made adjustments to the alignment of navbar elements. I’m attaching images of these changes for your review. Could you please take a look and let me know if there are any additional adjustments I should consider?

1) 
![propacity-navbar](https://github.com/user-attachments/assets/8c161cdb-2e55-4b4e-b857-afcca946994f)

2)
![propacity-navbar-2](https://github.com/user-attachments/assets/ee5a24c4-f5eb-40ef-a3be-05daf79bc835)

**Comment by adaharshsingh** [comment]
Yeah , it seems Good ! i will be able to review it better after you make a PR
