### ISSUE TITLE
Adding Feature of Current Location for accessing Weather forecast.

### ISSUE THREAD

**Issue by RishabhSri17** [adaharshsingh/Propacity#25]
Problem: Currently, there is no option for accessing the weather forecast of the user's current location. The application only allows access to the weather data for locations listed in the /assets/cities.json file.

Screenshots:
Current Website having Cities option or Search city Option.
![Screenshot 2024-10-06 173218](https://github.com/user-attachments/assets/067eab77-cac5-4726-8086-528aabb80bb7)
Only Weather Forecast data for Cities present in cities.json is accessed .
![Screenshot 2024-10-06 174054](https://github.com/user-attachments/assets/d5b15621-b731-4395-859f-3a780a6329f8)

Proposed Solution: I propose adding a new feature that allows users to fetch the weather forecast for their current location by utilizing the browser's Geolocation API. This will enable users to retrieve the weather forecast based on their latitude and longitude. The feature will include a new card in the city selection area labeled "Your Location," which, when clicked, will request the user's location and display the relevant weather data.

I have already implemented the LocationCard component, which integrates the Geolocation API to fetch the user's current coordinates and retrieve weather data using these coordinates through the Visual Crossing Weather API.

Changes Implemented:
- Added a LocationCard component that, when clicked, fetches the user's current latitude and longitude using the Geolocation API.
- Applied same styling to the LocationCard to match the existing CityCard layout.
- Integrated the fetched coordinates into the existing weather API to display the weather forecast for the user's current location.

Please assign this issue to me, and kindly add the Hacktoberfest tag for tracking.

**Comment by adaharshsingh** [comment]
Go Ahead!!!

**Comment by RishabhSri17** [comment]
I had added the feature of Current Location and it is working fine . Added screenshot for same .

![Screenshot 2024-10-07 021544 (2)](https://github.com/user-attachments/assets/7808fa5a-edd8-4791-8222-8e623860d25b)

I am also working on displaying place names instead of latitude and longitude for a better user interface, and I would like to add this feature in my next PR if given the chance.

Please accept my pull request #26  and review the changes and let me know if any adjustments are needed. Thank you!
