### ISSUE TITLE
Red Cross on "This place doesn't exist" Pop-up is Not Functional

### ISSUE THREAD

**Issue by adaharshsingh** [adaharshsingh/Propacity#28]
### Description:
When a user searches for a place that doesn't exist or provides invalid coordinates, a pop-up with a red cross is supposed to appear to notify the user. However, while the pop-up shows up, the red cross icon itself is not functional—clicking on it does not close the pop-up or provide any feedback.

### Current Behavior:
The pop-up with the red cross appears when an invalid place is searched.
Clicking the red cross does nothing—it doesn’t close the pop-up or perform any action.
### Expected Behavior:
The red cross should close the pop-up when clicked.

**Comment by chow870** [comment]
I am interested. Plz assign it to me

**Comment by rithvikreddybasani** [comment]
i can correct it. Plz assign this work to me
