### ISSUE TITLE
Enhance Search Bar Design for Better UI Integration

### ISSUE THREAD

**Issue by adaharshsingh** [adaharshsingh/Propacity#3]
The current search bar design could be visually enhanced to better align with the overall user interface. The goal is to improve the aesthetic appeal, making the search bar blend seamlessly with the design of the website/application.

### Proposed Improvements:

- Styling & Colors: Adjust the color scheme, borders, and shadows of the search bar to match the overall theme, ensuring it looks cohesive with other UI elements.

- Rounded Edges & Shadows: Consider adding subtle rounded edges and shadows to give the search bar a modern, clean look.

- Responsive Design: Ensure the search bar scales well on different screen sizes and devices, with a sleek, minimalistic appearance.

- Focus Animation: Add a smooth focus animation (e.g., highlighting or enlarging) when the user clicks on the search bar, making it more interactive and visually engaging.
### Current Behavior:

- The search bar feels disconnected from the rest of the design.
- It lacks modern styling and visual appeal.

### Expected Behavior:

- The search bar should blend naturally with the UI, adding to the overall aesthetics of the page without standing out in an awkward way.
- It should feel intuitive, modern, and visually engaging.

**Comment by PratikMane0112** [comment]
Interested in the issue, plz assign it to me under hactoberfest 2024.

**Comment by adaharshsingh** [comment]
Go for it !!!
