### ISSUE TITLE
Adding 404 error page 

### ISSUE THREAD

**Issue by PratikMane0112** [adaharshsingh/Propacity#4]
## Issue : In the current situation of project, if user hits  invalid URL then website is missing with 404 error page to render them back to homepage.

- Screenshot : 

![Screenshot 2024-10-01 200524](https://github.com/user-attachments/assets/a7e3117e-9303-45a9-8b01-4bd176e4c166)

## Work to do : 

- I will add a appropriate a 404 error page which matches with the website background.
- I will start working after assigning the issue & complete it in 2 days.

## Request for contribution :

- Please, assign me this task under hactoberfest 2024

**Comment by adaharshsingh** [comment]
Looking forward to your contribution

**Comment by PratikMane0112** [comment]
To solve this issue, its needs to install react-router npm package, should i proceed with it.

**Comment by adaharshsingh** [comment]
yeah , go Ahead!!

**Comment by prathameshkhandare** [comment]
@PratikMane0112 can u assign this to me

**Comment by PratikMane0112** [comment]
@prathameshkhandare all the four issues of mine has been resolved !!! Try for other one. Happy coding :)
