### ISSUE TITLE
Adding Favicon & title

### ISSUE THREAD

**Issue by PratikMane0112** [adaharshsingh/Propacity#5]
## Issue : In the current situation of project, web page is missing favicon & title.

- Screenshot : 

![Screenshot 2024-10-01 201333](https://github.com/user-attachments/assets/c58afc69-f602-45a7-a749-9c7c80286d37)

## Work to do : 

- I will add a appropriate `favicon` & `Popacity` tilte in navbar to have website as its own identity.
- I will start working after assigning the issue & complete it in 2 days.

## Request for contribution :

- Please, assign me this task under hactoberfest 2024

**Comment by adaharshsingh** [comment]
Nice catch !! I Never noticed it .
